name: gofmt govet goimports gocyclo
on: [push, pull_request]

jobs:
  static_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: gofmt
        run: |
          test -z $(gofmt -l .)
      
      - name: govet
        run: |
          test -z $(go vet ./...)
      
      - name: goimports
        run: |
          go get -d golang.org/x/tools/cmd/goimports
          test -z $(goimports -l .)
      
      - name: gocyclo
        run: |
          go get -d github.com/fzipp/gocyclo/cmd/gocyclo
          test -z $(gocyclo -over 25 .)
      
      - name: unittest
        run: |
          make unittest
